ARG APP_IMAGE=ubuntu:20.04

FROM $APP_IMAGE
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y awscli && rm -rf /var/lib/apt/lists/*
COPY seeder/seedtos3.sh /root/seedtos3.sh
RUN chmod +x /root/seedtos3.sh
ENTRYPOINT ["/root/seedtos3.sh"]
